- name: Check if mount dir exists (if it does we assume the disk is mounted)
  stat: path={{ mount_dir }}
  register: stat_mount_dir

- name: Create mount dir
  file: path={{ mount_dir }} state=directory
  when: stat_mount_dir.stat.exists == false

- name: Set mount options
  set_fact:
    mount_options_with_flag: "-o {{mount_options}}"
  when: mount_options is defined

- name: Mount google ssd
  command: >
    sudo /usr/share/google/safe_format_and_mount -m "mkfs.ext4 -F"
    {{mount_options_with_flag}}
    {{disk_device_path}} {{mount_dir}}

- name: Persist the mount
  become: true
  lineinfile: dest=/etc/fstab line="{{disk_device_path}} {{mount_dir}} ext4 {{mount_options}} 0 0"
  when: stat_mount_dir.stat.exists == false
